name: Deploy .Net Core 3.1 Azure Function App
#note: the deployment action generated at Azure is all wrong. Replace the deployment with this
#      However, make sure ot note the secret id and use that in the last part of the deployment
#      Also, do not forget to update the AZURE_FUNCTIONAPP_NAME
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: APIMFunctionsDemo-xyz123
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  DOTNET_VERSION: 'v3.1.417' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
          
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_abcdefghijklmnopqrstuvwxyz0123456789 }}
#note: The publish profile is generated by the deployment action.

